services:
  postgres:
    image: postgres:15-alpine
    container_name: trust-server-postgres-local
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword123
      # Performance tuning
      POSTGRES_SHARED_PRELOAD_LIBRARIES: pg_stat_statements
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - trust-network

  # pgAdmin for database administration
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: trust-server-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - trust-network

  # pg_exporter for monitoring (Prometheus metrics)
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: trust-server-postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:devpassword123@postgres:5432/postgres?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - trust-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  trust-network:
    driver: bridge
    name: trust-network
